services:
  weather-api:
    build:
      context: .. 
      dockerfile: pipeline/Dockerfile
    image: "weather-api:${VERSION}"  
    container_name: "weather-api"  
    ports:
      - "9574:9574"
    environment:
      - VERSION=${VERSION}  
