apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: docker.io/n1az/weather-api:2.4.3
          ports:
            - containerPort: 9574
          env:
            - name: CITY
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: CITY
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: API_KEY
