apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
spec:
  type: NodePort
  selector:
    app: weather-api
  ports:
    - port: 9574
      targetPort: 9574
      protocol: TCP
      nodePort: 30074  
